name: LaTeX Compilation

on:
  push:
    branches:
      - main  # Adjust branch name if necessary
  pull_request:
    branches:
      - main  # Adjust branch name if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: template.tex  # Adjust if your main LaTeX file has a different name
        packages:                   # Add any additional LaTeX packages you need
          - graphicx
          - hyperref

    - name: Compile LaTeX
      run: |
        pdflatex -interaction=nonstopmode -halt-on-error template.tex
        pdflatex -interaction=nonstopmode -halt-on-error template.tex  # Run twice for correct references

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: compiled-pdf
        path: |
          template.pdf
