name: LaTeX Compilation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cache TeX Live installation
      uses: actions/cache@v2
      with:
        path: /usr/local/texlive
        key: texlive-${{ runner.os }}

    - name: Install TeX Live
      if: steps.cache.outputs.cache-hit != 'true'  # Skip installation if cache hit
      run: sudo apt-get install -y texlive-full

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Compile LaTeX
      run: |
        pdflatex -interaction=nonstopmode -halt-on-error main.tex
        pdflatex -interaction=nonstopmode -halt-on-error main.tex

    - name: Upload PDF to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        keep_files: true
        publish_branch: gh-pages
